"""Form A5, A6, and A7 (ISAR) DOCX generators for user editing.

PVARA-compliant .docx output — MLRO/CEO can edit before signing.
"""

from datetime import datetime, timezone
from io import BytesIO
from typing import Any

from docx import Document
from docx.shared import Pt


def _get_register(tenant: Any) -> list[dict[str, Any]]:
    """Return outsourcing register from tenant config or default."""
    reg = getattr(tenant, "outsourcing_register", None)
    if reg is not None and isinstance(reg, list) and len(reg) > 0:
        return reg
    from app.modules.compliance.forms import DEFAULT_OUTSOURCING_REGISTER
    return DEFAULT_OUTSOURCING_REGISTER


def _bool_display(val: Any) -> str:
    if isinstance(val, bool):
        return "Yes" if val else "No"
    if isinstance(val, str):
        return "Yes" if val.lower() in ("yes", "true", "1") else "No"
    return "No"


def generate_form_a5_docx(tenant: Any) -> bytes:
    """Generate Form A5 (Outsourcing Register) as editable DOCX."""
    register = _get_register(tenant)
    tenant_name = getattr(tenant, "name", "VASP")
    tenant_slug = getattr(tenant, "slug", "") or "(tenant)"
    now = datetime.now(timezone.utc).strftime("%d %B %Y")

    doc = Document()
    doc.add_heading("Form A5 — Outsourcing Register", 0)
    p = doc.add_paragraph()
    p.add_run("PVARA NOC Regulation Annex A — Outsourcing Declaration and Register").italic = True

    doc.add_paragraph()
    doc.add_paragraph(f"Reporting Entity: {tenant_name}")
    doc.add_paragraph(f"Reference: {tenant_slug}")
    doc.add_paragraph(f"Date: {now}")

    doc.add_heading("Outsourced Services Register", level=1)

    headers = [
        "#", "Service Provider", "Country", "Function Outsourced", "AML/CFT Relevance",
        "Data Shared", "SLA Summary", "Audit Rights", "Sub-Out", "Termination Rights",
        "Risk Assessment", "Monitor Freq",
    ]
    table = doc.add_table(rows=1, cols=len(headers))
    table.style = "Table Grid"
    hdr = table.rows[0].cells
    for i, h in enumerate(headers):
        hdr[i].text = h

    for i, entry in enumerate(register, 1):
        func_outsourced = entry.get("functionOutsourced", "")
        if not func_outsourced:
            functions = entry.get("functions", [])
            func_outsourced = ", ".join(str(f) for f in functions) if isinstance(functions, list) else str(functions)

        row = table.add_row().cells
        row[0].text = str(i)
        row[1].text = str(entry.get("provider", ""))
        row[2].text = str(entry.get("countryOfIncorporation", entry.get("country", "")))
        row[3].text = str(func_outsourced)
        row[4].text = str(entry.get("amlCftRelevance", ""))
        row[5].text = str(entry.get("dataShared", ""))
        row[6].text = str(entry.get("slaSummary", ""))
        row[7].text = _bool_display(entry.get("auditRights"))
        row[8].text = _bool_display(entry.get("subOutsourcingPermitted"))
        row[9].text = str(entry.get("terminationRights", "Standard"))
        row[10].text = str(entry.get("riskAssessment", "Medium"))
        row[11].text = str(entry.get("monitoringFrequency", "Quarterly"))

    doc.add_paragraph()
    doc.add_heading("Compliance Officer Declaration", level=1)
    doc.add_paragraph(
        "I confirm that this outsourcing register is accurate and complete as of the date stated above. "
        "All outsourced functions have been assessed for AML/CFT risk and appropriate controls, "
        "monitoring, and contractual safeguards are in place in accordance with PVARA regulations."
    )
    doc.add_paragraph(
        "Outsourcing does not relieve the reporting entity of its compliance obligations under "
        "the PVARA framework and NOC Regulation 14."
    )
    doc.add_paragraph()
    doc.add_paragraph("Name: _________________________")
    doc.add_paragraph("Title: _________________________")
    doc.add_paragraph("Signature: _________________________")
    doc.add_paragraph("Date: _________________________")

    doc.add_paragraph()
    doc.add_paragraph(
        "Generated by CIP. Outsourcing does not relieve the reporting entity of compliance responsibility. PVARA NOC Reg. 14 applies."
    ).runs[0].font.size = Pt(8)

    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()


def generate_form_a6_docx(tenant: Any, stats: dict, year: int) -> bytes:
    """Generate Form A6 (Annual AML/CFT Return) as editable DOCX."""
    tenant_name = getattr(tenant, "name", "VASP")
    tenant_slug = getattr(tenant, "slug", "") or "(tenant)"
    now = datetime.now(timezone.utc).strftime("%d %B %Y")

    manual = stats.get("manualInput", {}) or {}
    s1 = manual.get("entityProfile", {}) or {}
    s2 = manual.get("governance", {}) or {}
    s3 = manual.get("riskAssessment", {}) or {}
    s7 = manual.get("independentAudit", {}) or {}

    doc = Document()
    doc.add_heading("Form A6 — Annual AML/CFT Return", 0)
    p = doc.add_paragraph()
    p.add_run("PVARA Part 6 — Annual Compliance Return").italic = True

    doc.add_paragraph()
    doc.add_paragraph(f"Reporting Entity: {tenant_name}")
    doc.add_paragraph(f"Reference: {tenant_slug}")
    doc.add_paragraph(f"Reporting Year: {year}")
    doc.add_paragraph(f"Reporting Period: 1 January {year} — 31 December {year}")
    doc.add_paragraph(f"Generated: {now}")

    def add_section(title: str, rows: list[tuple[str, str]]):
        doc.add_heading(title, level=1)
        t = doc.add_table(rows=len(rows), cols=2)
        t.style = "Table Grid"
        for i, (label, val) in enumerate(rows):
            t.rows[i].cells[0].text = label
            t.rows[i].cells[1].text = str(val)
        doc.add_paragraph()

    add_section("1. Entity Profile", [
        ("Legal Name", s1.get("legalName", tenant_name)),
        ("PVARA Registration Number", s1.get("pvaraRegistrationNumber", "")),
        ("Reporting Period", f"1 January {year} — 31 December {year}"),
        ("Key Individuals (MLRO, CEO, Board)", s1.get("keyIndividuals", "")),
    ])

    add_section("2. Governance", [
        ("MLRO Annual Statement", s2.get("mlroAnnualStatement", "")),
        ("Changes in Governance Structure", s2.get("governanceChanges", "None")),
        ("Changes in Outsourcing Arrangements", s2.get("outsourcingChanges", "None")),
        ("AML/CFT Training Hours (Period)", stats.get("trainingHours", 0)),
    ])

    add_section("3. Risk Assessment Update", [
        ("New Risks Identified", s3.get("newRisks", "None identified")),
        ("Material Changes to Risk Profile", s3.get("materialChanges", "None")),
        ("Emerging Trends / Typologies", s3.get("emergingTrends", "None identified")),
    ])

    add_section("4. Customer Due Diligence Metrics", [
        ("Total Customers Onboarded", stats.get("customersOnboarded", 0)),
        ("High-Risk Customers", stats.get("customersHighRisk", 0)),
        ("Politically Exposed Persons (PEPs)", stats.get("customersPep", 0)),
        ("Customers Refused / Rejected", stats.get("customersRefused", 0)),
        ("Customers Exited / Off-boarded", stats.get("customersExited", 0)),
        ("Screenings Conducted", stats.get("screeningsConducted", 0)),
    ])

    add_section("5. Transaction Monitoring Metrics", [
        ("Total Alerts Generated", stats.get("alertsTotal", 0)),
        ("Alerts Escalated", stats.get("alertsEscalated", 0)),
        ("Alerts Closed / Resolved", stats.get("alertsClosed", 0)),
        ("Alerts Pending", stats.get("alertsPending", 0)),
    ])

    add_section("6. STR/CTR Reporting", [
        ("STRs Filed", stats.get("strsFiled", 0)),
        ("Categories of Suspicion", stats.get("suspicionCategories", "N/A")),
        ("CTRs Filed", stats.get("ctrsFiled", 0)),
    ])

    add_section("7. Independent Audit", [
        ("Findings Summary", s7.get("findingsSummary", "")),
        ("Remediation Status", s7.get("remediationStatus", "")),
        ("Outstanding Gaps", s7.get("outstandingGaps", "None")),
    ])

    doc.add_heading("8. Declaration", level=1)
    doc.add_paragraph(
        "We hereby declare that the information provided in this Annual AML/CFT Return is true, "
        "accurate, and complete to the best of our knowledge. We confirm that adequate policies, "
        "procedures, and controls are in place to ensure compliance with the PVARA framework and "
        "applicable AML/CFT regulations."
    )
    doc.add_paragraph()
    doc.add_paragraph("MLRO — Name: _________________________ Signature: _________________________ Date: _________________________")
    doc.add_paragraph("CEO / Managing Director — Name: _________________________ Signature: _________________________ Date: _________________________")

    doc.add_paragraph()
    doc.add_paragraph(
        f"Generated by CIP. Data aggregated for period 1 Jan {year} – 31 Dec {year}. PVARA Part 6 applies."
    ).runs[0].font.size = Pt(8)

    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()


def generate_fmu_freeze_report_docx(
    freeze_record: Any,
    tenant: Any,
    customer: Any,
) -> bytes:
    """Generate FMU Freeze Report (PVARA NOC Reg. 12.2) as editable DOCX.

    For reporting asset freezes of designated persons to FMU.
    """
    tenant_name = getattr(tenant, "name", "VASP") if tenant else "VASP"
    tenant_slug = getattr(tenant, "slug", "") or "(pending)"
    now = datetime.now(timezone.utc).strftime("%d %B %Y %H:%M UTC")

    cust_name = getattr(customer, "full_name", "") or ""
    cust_cnic = getattr(customer, "cnic_number", "") or "N/A"
    cust_nationality = getattr(customer, "nationality", "") or "N/A"

    freeze_type = str(getattr(freeze_record, "freeze_type", "") or "")
    matched_list = str(getattr(freeze_record, "matched_list", "") or "N/A")
    matched_name = str(getattr(freeze_record, "matched_name", "") or "N/A")
    match_score = getattr(freeze_record, "match_score", None)
    match_score_str = f"{match_score:.1f}%" if match_score is not None else "N/A"
    frozen_at = getattr(freeze_record, "frozen_at", None)
    frozen_at_str = frozen_at.strftime("%d %B %Y %H:%M UTC") if frozen_at else now
    notes = str(getattr(freeze_record, "notes", "") or "None")
    fr_id = str(getattr(freeze_record, "id", ""))[:8]

    doc = Document()
    doc.add_heading("ASSET FREEZE NOTIFICATION TO FMU", 0)
    p = doc.add_paragraph()
    p.add_run("PVARA NOC Regulation 12.2 — Targeted Financial Sanctions Compliance").italic = True
    doc.add_paragraph(f"Freeze Reference: {fr_id}")
    doc.add_paragraph()

    p_urgent = doc.add_paragraph()
    run = p_urgent.add_run(
        "URGENT: Assets frozen under Targeted Financial Sanctions obligations. "
        "Immediate reporting to FMU required."
    )
    run.bold = True

    def add_section(title: str, rows: list[tuple[str, str]]):
        doc.add_heading(title, level=1)
        t = doc.add_table(rows=len(rows), cols=2)
        t.style = "Table Grid"
        for i, (label, val) in enumerate(rows):
            t.rows[i].cells[0].text = label
            t.rows[i].cells[1].text = str(val) if val else ""
        doc.add_paragraph()

    add_section("1. Reporting Entity", [
        ("VASP Name", tenant_name),
        ("PVARA Registration", tenant_slug),
        ("Report Date", now),
    ])

    add_section("2. Designated Person / Customer", [
        ("Full Name", cust_name),
        ("CNIC / ID Number", cust_cnic),
        ("Nationality", cust_nationality),
    ])

    add_section("3. Sanctions Match Details", [
        ("Sanctions List Matched", matched_list),
        ("Matched Name on List", matched_name),
        ("Match Confidence Score", match_score_str),
        ("Freeze Type", freeze_type.replace("_", " ").title()),
    ])

    add_section("4. Freeze Action", [
        ("Date and Time of Freeze", frozen_at_str),
        ("Action Taken", "All virtual assets and accounts associated with the designated person "
         "have been immediately frozen. No transactions permitted pending further instruction from FMU."),
        ("Additional Notes", notes),
    ])

    doc.add_heading("5. Compliance Officer Declaration", level=1)
    doc.add_paragraph(
        "I hereby confirm that the above freeze action was taken immediately upon identification "
        "of the designated person, in accordance with PVARA NOC Regulation 12.2 and applicable "
        "Targeted Financial Sanctions obligations. No funds or virtual assets have been released "
        "or made available to the designated person since the time of the freeze."
    )
    doc.add_paragraph()
    doc.add_paragraph("Name: _________________________")
    doc.add_paragraph("Title: _________________________")
    doc.add_paragraph("Signature: _________________________")
    doc.add_paragraph("Date: _________________________")

    doc.add_paragraph()
    doc.add_paragraph(
        f"Generated by CIP for {tenant_name}. PVARA NOC Regulation 12.2 — Targeted Financial Sanctions."
    ).runs[0].font.size = Pt(8)

    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()


def generate_isar_docx(isar: Any, tenant: Any, customer: Any = None) -> bytes:
    """Generate Form A7 — Internal Suspicious Activity Report (ISAR) as editable DOCX.

    Matches PVARA NOC Annex A Form A7 structure:
      Section 1 — Reporter Details
      Section 2 — Customer Details
      Section 3 — Transaction Details
      Section 4 — Suspicion Narrative
      Section 5 — MLRO Determination
    """
    tenant_name = getattr(tenant, "name", "VASP") if tenant else "VASP"
    now = datetime.now(timezone.utc).strftime("%d %B %Y")

    reporter = getattr(isar, "reporter_details", None) or {}
    cust_details = getattr(isar, "customer_details", None) or {}
    tx_details = getattr(isar, "transaction_details", None) or {}
    mlro_det = getattr(isar, "mlro_determination", None) or {}
    narrative = getattr(isar, "narrative", "") or ""
    suspicion_type = getattr(isar, "suspicion_type", "") or ""
    evidence = getattr(isar, "supporting_evidence", None) or {}
    status = getattr(isar, "status", None)
    status_str = status.value if hasattr(status, "value") else str(status or "draft")

    customer_name = ""
    customer_cnic = ""
    if customer:
        customer_name = getattr(customer, "full_name", "") or ""
        customer_cnic = getattr(customer, "cnic_number", "") or ""
    if not customer_name:
        customer_name = cust_details.get("customerName", "")
    if not customer_cnic:
        customer_cnic = cust_details.get("customerId", "")

    doc = Document()
    doc.add_heading("Form A7 — Internal Suspicious Activity Report (ISAR)", 0)
    p = doc.add_paragraph()
    p.add_run("PVARA NOC Annex A — PVARA/REG/AML-REG/2025-1").italic = True
    doc.add_paragraph()
    doc.add_paragraph(f"Reporting Entity: {tenant_name}")
    doc.add_paragraph(f"ISAR Reference: {str(getattr(isar, 'id', ''))[:8]}")
    doc.add_paragraph(f"Status: {status_str}")
    doc.add_paragraph(f"Generated: {now}")

    def add_section(title: str, rows: list[tuple[str, str]]):
        doc.add_heading(title, level=1)
        t = doc.add_table(rows=len(rows), cols=2)
        t.style = "Table Grid"
        for i, (label, val) in enumerate(rows):
            t.rows[i].cells[0].text = label
            t.rows[i].cells[1].text = str(val) if val else ""
        doc.add_paragraph()

    add_section("Section 1 — Reporter Details", [
        ("1.1 Name", reporter.get("reporterName", "")),
        ("1.2 Position", reporter.get("reporterPosition", "")),
        ("1.3 Date of Report", reporter.get("reportDate", now)),
    ])

    wallet_addrs = cust_details.get("walletAddresses", evidence.get("walletAddresses", []))
    account_nums = cust_details.get("accountNumbers", [])
    add_section("Section 2 — Customer Details", [
        ("2.1 Customer Name / ID", f"{customer_name} — {customer_cnic}" if customer_cnic else customer_name),
        ("2.2 Wallet Addresses", ", ".join(wallet_addrs) if isinstance(wallet_addrs, list) else str(wallet_addrs)),
        ("2.3 Account Numbers", ", ".join(account_nums) if isinstance(account_nums, list) else str(account_nums)),
    ])

    tx_dates = tx_details.get("transactionDates", [])
    tx_amounts = tx_details.get("amounts", [])
    add_section("Section 3 — Transaction Details", [
        ("3.1 Date(s)", ", ".join(tx_dates) if isinstance(tx_dates, list) else str(tx_dates)),
        ("3.2 Amount(s)", ", ".join(str(a) for a in tx_amounts) if isinstance(tx_amounts, list) else str(tx_amounts)),
        ("3.3 Type of Transaction", tx_details.get("transactionType", "")),
        ("3.4 On-chain / Off-chain Details", tx_details.get("onChainDetails", "") or tx_details.get("offChainDetails", "")),
    ])

    doc.add_heading("Section 4 — Suspicion Narrative", level=1)
    doc.add_paragraph(f"Suspicion Type: {(suspicion_type or '').replace('_', ' ').title()}")
    doc.add_paragraph()
    doc.add_paragraph(narrative or "(Describe the relevant facts, observed behaviour, identified indicators, and any applicable red flags.)")
    doc.add_paragraph()
    alert_ids = evidence.get("alertIds", [])
    if alert_ids:
        doc.add_paragraph(f"Linked Alert IDs: {', '.join(str(a) for a in alert_ids)}")

    doc.add_heading("Section 5 — MLRO Determination", level=1)
    det_table = doc.add_table(rows=4, cols=2)
    det_table.style = "Table Grid"
    det_table.rows[0].cells[0].text = "Determination"
    det_table.rows[0].cells[1].text = mlro_det.get("determination", "☐ File as STR   ☐ Do Not File   ☐ Additional Info Required")
    det_table.rows[1].cells[0].text = "MLRO Notes"
    det_table.rows[1].cells[1].text = mlro_det.get("determinationNotes", "")
    det_table.rows[2].cells[0].text = "MLRO Name"
    det_table.rows[2].cells[1].text = mlro_det.get("mlroName", "_________________________")
    det_table.rows[3].cells[0].text = "MLRO Signature Date"
    det_table.rows[3].cells[1].text = mlro_det.get("mlroSignatureDate", "_________________________")
    doc.add_paragraph()
    doc.add_paragraph("MLRO Signature: _________________________")

    rejection = getattr(isar, "rejection_rationale", None)
    if rejection:
        doc.add_paragraph()
        doc.add_paragraph(f"Rejection Rationale: {rejection}")

    doc.add_paragraph()
    doc.add_paragraph(
        f"Generated by CIP for {tenant_name}. Form A7 per PVARA NOC Annex A. "
        "VASPs may use their own ISAR format provided it includes the above minimum information."
    ).runs[0].font.size = Pt(8)

    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()
